Integrated Github api to fetch contributors
SrijanShovit/carbonops-v2 pull request #107
Opened 2023-06-14 19:04 UTC by Ida-Naliaka

## Related Issue

To render details of contributors of this repo in the about us page using the github api to fetch data.
To ensure that clicking a contributor's card will redirect to that contributor's github profile

Closes: #44

## Description of Changes

- Added a new function to handle fetching data from the Github API and runs on initial load.
-  Removed hard coded json data in the team component and used fetched data to render contributors info.
- Clicking the teamcard component redirects to the contributor's github profile
- Updated the next.config.js file to allow external images particularly github avatars.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| ![Original screenshot](https://github.com/SrijanShovit/carbonops-v2/assets/103431191/8387dbf0-48a8-49f7-9268-8bff5dce644b) | ![Updated screenshot](https://github.com/SrijanShovit/carbonops-v2/assets/103431191/b8346925-3f59-4c66-a313-c7bc045a8a2f) |

2023-06-14 19:04 UTC, SrijanShovit reviewed
Hello Ida-Naliaka, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

2023-06-15 01:20 UTC, shreya024 requested changes
Hey @Ida-Naliaka Great work on integrating the Github API.Could you change the image layout and make them look rounded

2023-06-15 09:08 UTC, Ida-Naliaka commented
Hi @shreya024  I've changed the image styling to rounded. 
Here's the screenshot
![New update](https://github.com/SrijanShovit/carbonops-v2/assets/103431191/17ea9ee7-3742-46e4-a054-e932d9006b0f)

2023-06-15 11:40 UTC, shreya024 approved these changes
LGTM!

2023-06-20 01:07 UTC, merged