added the protectRoute middleware for non authenticated user
SrijanShovit/carbonops-v2 pull request #157
Opened 2023-06-25 18:19 UTC by Akash-gahlot

Issue : #118 

@shreya024 

 IMPORTANT --> For testing purpose i have  set isLogged value to false in protectRoute and did a small modification in aboutus route so a user without login cannot access the aboutus page , because we dont have any route apart from these /home,/aboutus,/contactus,/login,/signup so i choose aboutus page for testing purpose.
we can revert the aboutus code changes later after testing the protectRoute working.

https://github.com/SrijanShovit/carbonops-v2/assets/71133465/4ddc0140-ab73-45d8-8e54-f6f3d25d81be

2023-06-25 18:19 UTC, SrijanShovit reviewed
Hello Akash-gahlot, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

2023-06-26 01:22 UTC, shreya024 requested changes

2023-06-26 01:22 UTC, shreya024 commented on app/aboutus/page.js
> +//for testing purpose added the protectRoute please remove the protectRoute from here to access this page.
Could you test it on /calculate,rather than on the /aboutus

2023-06-27 18:05 UTC, Akash-gahlot commented on app/aboutus/page.js
> +//for testing purpose added the protectRoute please remove the protectRoute from here to access this page.
completed the required fixed @shreya024 , could you please validate the changes and approve.

2023-06-29 02:15 UTC, shreya024 requested changes
@Akash-gahlot Resolve the vercel error. Everything else LGTM!

2023-06-29 14:42 UTC, Akash-gahlot commented
@shreya024 when i clicked on vercel error  so it shows commit  is pending for approval from @SrijanShovit  ,
can you confirm am i correct here or something from my side only is pending?
please have look on this below image.

![image](https://github.com/SrijanShovit/carbonops-v2/assets/71133465/6625c5f8-e969-4ef8-afd1-3e8c2c48a702)

2023-07-03 01:39 UTC, shreya024 commented
@Akash-gahlot Resolve the conflicts and push again

2023-07-03 12:29 UTC, closed without merging