feat: Developed products page UI
SrijanShovit/carbonops-v2 pull request #171
Opened 2023-07-03 03:16 UTC by MahendraDani

## Related Issue

Closes: #138 

## Description of Changes

- Developed products Page UI as per the given designs.
- The route of the page is `http://localhost:3000/products`
- The design is fully responsive for mobile, tablet and desktop screens.
## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots
Please provide any necessary screenshots to illustrate the changes made.

https://github.com/SrijanShovit/carbonops-v2/assets/116940083/bd745b48-808a-4d3d-bd6f-5851bba08720

2023-07-03 03:16 UTC, SrijanShovit reviewed
Hello MahendraDani, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

2023-07-03 03:17 UTC, MahendraDani commented
@shreya024 This is the fresh PR for the issue.
Please review the PR and let me know if there are any changes!

2023-07-03 06:18 UTC, SrijanShovit commented
Everything looks good 
Just change $ to rupees😂
@MahendraDani

2023-07-03 07:02 UTC, MahendraDani commented
@shreya024 @SrijanShovit  Changed the dollars symbol to ruppee symbol.
![Capture_carbonops](https://github.com/SrijanShovit/carbonops-v2/assets/116940083/327e42af-dbfc-437a-ab14-21bb8f1997f2)

2023-07-04 02:19 UTC, shreya024 requested changes

2023-07-04 02:19 UTC, shreya024 commented on app/products/page.js
> +import sampleImg from "../../public/images/homepage/documents.png";
Change Image imports as per #158

2023-07-04 02:19 UTC, shreya024 commented on app/products/page.js
> +        " Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem quis qui accusamus odit similique, expedita velit at cupiditate dolor iure? Laboriosam repudiandae quod pariatur necessitatibus
Resolve vercel Error

2023-07-04 02:47 UTC, shreya024 commented
@MahendraDani This is the vercel error for your reference

[08:12:47.276] Running "vercel build"
[08:12:47.761] Vercel CLI 31.0.1
[08:12:47.981] Error while parsing config file: "/vercel/path0/package-lock.json"
[08:12:47.986] Error while parsing config file: "/vercel/path0/package-lock.json"
[08:12:47.990] Error while parsing config file: "/vercel/path0/package-lock.json"
[08:12:47.991] Installing dependencies...
[08:12:48.244] yarn install v1.22.17
[08:12:48.300] warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[08:12:48.302] [1/4] Resolving packages...
[08:12:50.218] [2/4] Fetching packages...
[08:13:19.313] [3/4] Linking dependencies...
[08:13:19.316] warning " > bootstrap@5.3.0" has unmet peer dependency "@popperjs/core@^2.11.7".
[08:13:19.317] warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[08:13:19.317] warning " > mdb-react-ui-kit@6.1.0" has unmet peer dependency "@types/react@^18.0.9".
[08:13:19.317] warning " > mdb-react-ui-kit@6.1.0" has unmet peer dependency "@types/react-dom@^18.0.3".
[08:13:19.318] warning " > styled-components@5.3.11" has unmet peer dependency "react-is@>= 16.8.0".
[08:13:49.751] [4/4] Building fresh packages...
[08:13:50.370] success Saved lockfile.
[08:13:50.374] Done in 62.13s.
[08:13:50.404] Detected Next.js version: 13.4.6
[08:13:50.406] Error while parsing config file: "/vercel/path0/package-lock.json"
[08:13:50.407] Running "yarn run build"
[08:13:50.578] yarn run v1.22.17
[08:13:50.601] $ next build
[08:13:51.060] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[08:13:51.061] This information is used to shape Next.js' roadmap and prioritize features.
[08:13:51.061] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[08:13:51.061] https://nextjs.org/telemetry
[08:13:51.061] 
[08:13:51.151] - info Creating an optimized production build...
[08:13:51.292] SyntaxError: Unexpected string in JSON at position 75956
[08:13:51.293]     at JSON.parse (<anonymous>)
[08:13:51.293]     at patchIncorrectLockfile (/vercel/path0/node_modules/next/dist/lib/patch-incorrect-lockfile.js:93:33)
[08:14:00.937] - info Compiled successfully
[08:14:00.939] - info Linting and checking validity of types...
[08:14:02.654] 
[08:14:02.654] Failed to compile.
[08:14:02.655] 
[08:14:02.655] ./app/products/page.js
[08:14:02.655] 45:13  Error: Missing "key" prop for element in iterator  react/jsx-key
[08:14:02.655] 
[08:14:02.655] info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
[08:14:02.706] error Command failed with exit code 1.
[08:14:02.707] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[08:14:02.721] Error: Command "yarn run build" exited with 1

2023-07-05 02:15 UTC, MahendraDani commented
@shreya024 I have used `npm` to install some dependencies . Is that the cause of error?
Do we use `yarn` package manager in our project?

2023-07-05 02:32 UTC, shreya024 commented
> @shreya024 I have used `npm` to install some dependencies . Is that the cause of error? Do we use `yarn` package manager in our project?

No no npm is the way to go...other errors I've commented like  Missing "key" prop for element in iterator react/jsx-key in ./app/products/page.js

2023-07-05 02:57 UTC, MahendraDani commented
@shreya024 I have tried to resolve vercel errors in this [commit](https://github.com/SrijanShovit/carbonops-v2/pull/171/commits/6fe83c96b6f8b9e822621c799af3a80c3a84966c).

If there are still any errors please guide me!

2023-07-06 02:01 UTC, shreya024 requested changes

2023-07-06 02:01 UTC, shreya024 commented on app/products/page.js
> +            <div className="mt-4">
provide a key as id

2023-07-06 03:12 UTC, MahendraDani commented
@shreya024 Added a key as `id`

2023-07-06 03:12 UTC, MahendraDani commented on app/products/page.js
> +            <div className="mt-4">
Added key as id

2023-07-06 16:28 UTC, shreya024 requested changes

2023-07-06 16:28 UTC, shreya024 commented on app/products/page.js
> +            <div className="mt-4" id={product.id}>
Change line 46 to this <div className="mt-4" key={product.id}>

2023-07-07 14:18 UTC, MahendraDani commented on app/products/page.js
> +            <div className="mt-4" id={product.id}>
@shreya024 I changed this to line 46 already!

2023-07-09 05:07 UTC, shreya024 commented
@MahendraDani Change line 46 to this <div className="mt-4" key={product.id}>

2023-07-09 12:31 UTC, MahendraDani commented
> @MahendraDani Change line 46 to this `<div className="mt-4" key={product.id}>`

@shreya024 I made the necessary changes , please review the PR

2023-07-10 01:37 UTC, shreya024 approved these changes

2023-07-10 01:37 UTC, merged