navbar improvement
SrijanShovit/carbonops-v2 pull request #172
Opened 2023-07-03 06:17 UTC by SubhamB2003

## Related Issue
issue solved: #166 

Closes: #[issue number]

## Description of Changes

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| ![Original screenshot](link) | ![Updated screenshot](link) |

Please provide any necessary screenshots to illustrate the changes made.

2023-07-03 06:18 UTC, SrijanShovit reviewed
Hello SubhamB2003, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

2023-07-05 01:33 UTC, shreya024 commented on yarn.lock
@SubhamB2003 Resolve the merge conflicts

2023-07-05 04:40 UTC, SubhamB2003 commented on yarn.lock
Done

2023-07-07 14:41 UTC, SubhamB2003 commented
@shreya024 Hey, can you please review it

2023-07-09 05:09 UTC, shreya024 requested changes
@SubhamB2003 Resolve the conflicts

2023-07-09 05:21 UTC, SubhamB2003 commented
@shreya024 done.

2023-07-18 02:08 UTC, shreya024 commented
> @shreya024 Can you please merge my pr?

@SubhamB2003 Take a pull,resolve merge conflicts and make sure your code adheres to the changed folder structure

2023-07-18 06:46 UTC, SubhamB2003 commented
@shreya024 Hey, the navbar issue is already fixed by someone 🥲

previously it showed this
![image](https://github.com/SrijanShovit/carbonops-v2/assets/94003231/d49936bb-b84a-4ac8-9f01-dca4dae9f2af)

but currently, it is showing this 
![image](https://github.com/SrijanShovit/carbonops-v2/assets/94003231/fbf9dec6-fc95-4687-97d8-619c1cd4a3e0)

2023-07-20 17:36 UTC, SubhamB2003 commented
@shreya024 Please merge my pr

2023-07-21 01:31 UTC, shreya024 approved these changes

2023-07-21 01:31 UTC, merged