Spelling corrected
SrijanShovit/carbonops-v2 pull request #204
Opened 2023-07-14 16:40 UTC by accodes21

## Related Issue

Closes: #178 

## Description of Changes

Corrected the spelling of audience in ReadME file
## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| 
![Screenshot (349)](https://github.com/SrijanShovit/carbonops-v2/assets/101868279/b0ca4d45-bbf2-499b-9b22-e678b186958e)| 
![Screenshot (350)](https://github.com/SrijanShovit/carbonops-v2/assets/101868279/3ff0394a-404c-4f3c-a20b-ab80a0abe7f8)|

2023-07-14 16:41 UTC, SrijanShovit reviewed
Hello accodes21, thanks for rising a Pull request, your contribution is valuable to us. The maintainers will review this Pull Request and provide feedback as soon as possible. Keep the great work up!<p></p>

2023-07-17 01:49 UTC, shreya024 requested changes
@accodes21 Correct any other spelling mistakes,if there

2023-07-17 05:19 UTC, accodes21 commented
> @accodes21 Correct any other spelling mistakes,if there

Checked all, found no other mistake.

2023-07-26 16:05 UTC, shreya024 approved these changes

2023-07-26 16:05 UTC, merged