feat: Created signup page for individuals and organizations
SrijanShovit/carbonops-v2 pull request #35
Opened 2023-05-28 12:19 UTC by MahendraDani

Fixes #19 

## Outcomes
1. Created login page for both individuals and organizations.
2. The route for individual signup is `http://localhost:3000/signup/individual`.
3. The route for organizations signup is `http:localhost:3000/signup/organization`.
4. Fixed imports of images in `home page`.
5. All the pages are **fully responsive** for seamless user experience.
6. Added `graph` image in `homepage`.
## Video/Screenshots

https://github.com/SrijanShovit/carbonops-v2/assets/116940083/31b4b69b-7639-47fe-b499-509b2abeeabb

2023-05-28 12:20 UTC, MahendraDani commented
@shreya024 Please review the changes.
If there are any changes please let me know!
Thanks!

2023-05-28 14:43 UTC, shreya024 commented
> @shreya024 Please review the changes. If there are any changes please let me know! Thanks!

Hey @MahendraDani Please remove all warnings in your console,so that vercel can deploy successfully

2023-05-28 14:44 UTC, MahendraDani commented
@shreya024 How should I clear the vercel test?
Do I need to commit again ?
Please help me out!

2023-05-28 14:45 UTC, shreya024 requested changes

2023-05-28 14:45 UTC, shreya024 commented on app/signup/individual/page.js
> +                <Image src={welcomeImage} height={500} width={500} />
Add alt tags to all <Image> tags

2023-05-28 14:47 UTC, MahendraDani commented on app/signup/individual/page.js
> +                <Image src={welcomeImage} height={500} width={500} />
Will try to resolve all warnings by tonight!
Thanks!

2023-05-28 14:49 UTC, shreya024 commented
> @shreya024 How should I clear the vercel test? Do I need to commit again ? Please help me out!

When you run the app on localhost,right-click and click on Inspect ->go to console->you will see a bunch of warnings like this
![image](https://github.com/SrijanShovit/carbonops-v2/assets/72400676/2f8a9559-c16f-494f-bc87-64cea7c35270)
just add the alt tags and any other changes as is shown in the console and push again

2023-05-28 15:29 UTC, MahendraDani commented
> > @shreya024 How should I clear the vercel test? Do I need to commit again ? Please help me out!
> 
> When you run the app on localhost,right-click and click on Inspect ->go to console->you will see a bunch of warnings like this ![image](https://user-images.githubusercontent.com/72400676/241567709-2f8a9559-c16f-494f-bc87-64cea7c35270.png) just add the alt tags and any other changes as is shown in the console and push again

@shreya024 Do I need to clear the yellow warnings as well? Because the dimensions of images are set which suits bests for the UI.

2023-05-28 15:35 UTC, shreya024 commented
> > > @shreya024 How should I clear the vercel test? Do I need to commit again ? Please help me out!
> > 
> > 
> > When you run the app on localhost,right-click and click on Inspect ->go to console->you will see a bunch of warnings like this ![image](https://user-images.githubusercontent.com/72400676/241567709-2f8a9559-c16f-494f-bc87-64cea7c35270.png) just add the alt tags and any other changes as is shown in the console and push again
> 
> @shreya024 Do I need to clear the yellow warnings as well? Because the dimensions of images are set which suits bests for the UI.

Push once with all red warnings cleared.If vercel fails again,you may need to work on the yellow warnings as well

2023-05-28 15:43 UTC, MahendraDani commented
@shreya024 I have resolved all the red warnings appearing in the console, still the Vercel test is failing.
Would you please tell me what should I do now?

2023-05-28 15:46 UTC, shreya024 commented
> @shreya024 I have resolved all the red warnings appearing in the console, still the Vercel test is failing. Would you please tell me what should I do now?

Try replacing ' in content with `&apos` 
For example: industry's will become industry `&apos` s

2023-05-28 15:55 UTC, MahendraDani commented
@shreya024 
What if I removed all the ' from the content?
Will it be fine for now?

Because once the pages are set up we can optimize the SEO using the alt tags later.
Right?

2023-05-28 15:58 UTC, shreya024 commented
> @shreya024 
> What if I removed all the ' from the content?
> Will it be fine for now?
> 
> Because once the pages are set up we can optimize the SEO using the alt tags later.
> Right?

Yeah sure,u can remove them for now

2023-05-28 15:59 UTC, MahendraDani commented
> > @shreya024
> > What if I removed all the ' from the content?
> > Will it be fine for now?
> > Because once the pages are set up we can optimize the SEO using the alt tags later.
> > Right?
> 
> Yeah sure,u can remove them for now

Removing them for now!

2023-05-28 16:13 UTC, MahendraDani commented
@shreya024 I have changed all `'` with `&apos;` in the codebase, still the vercel test is failing.
Now I can't think of any reason why it is failing?

2023-05-28 16:35 UTC, SrijanShovit commented
@shreya024 
[21:42:07.464] Running build in Washington, D.C., USA (East) – iad1
[21:42:07.523] Cloning github.com/SrijanShovit/carbonops-v2 (Branch: Mahendra/signup_page_branch, Commit: 2544b06)
[21:42:07.821] Cloning completed: 298.307ms
[21:42:10.710] Restored build cache
[21:42:10.739] Running "vercel build"
[21:42:11.254] Vercel CLI 29.3.6
[21:42:11.528] Installing dependencies...
[21:42:13.213] 
[21:42:13.214] added 1 package in 1s
[21:42:13.214] 
[21:42:13.214] 136 packages are looking for funding
[21:42:13.214]   run `npm fund` for details
[21:42:13.225] Detected Next.js version: 13.4.2
[21:42:13.227] Detected `package-lock.json` generated by npm 7+...
[21:42:13.228] Running "npm run build"
[21:42:13.538] 
[21:42:13.538] > carbonops-v2@0.1.0 build
[21:42:13.538] > next build
[21:42:13.539] 
[21:42:14.081] - info Creating an optimized production build...
[21:42:22.797] Failed to compile.
[21:42:22.797] 
[21:42:22.797] ./components/homepage/Services.js
[21:42:22.797] Module not found: Can't resolve '../../public/images/homepage/interview.png'
[21:42:22.798] 
[21:42:22.798] https://nextjs.org/docs/messages/module-not-found
[21:42:22.798] 
[21:42:22.798] Import trace for requested module:
[21:42:22.798] ./app/page.js
[21:42:22.798] 
[21:42:22.798] 
[21:42:22.799] > Build failed because of webpack errors
[21:42:22.839] Error: Command "npm run build" exited with 1
[21:42:23.031] BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

Problem in deployment

2023-05-28 16:40 UTC, shreya024 commented
@MahendraDani this is the error log. Kindly go through it and fix the bugs

2023-05-28 16:41 UTC, MahendraDani commented
@shreya024 yes mam!

2023-05-28 16:58 UTC, MahendraDani commented
> @shreya024 [21:42:07.464] Running build in Washington, D.C., USA (East) – iad1 [21:42:07.523] Cloning github.com/SrijanShovit/carbonops-v2 (Branch: Mahendra/signup_page_branch, Commit: [2544b06](https://github.com/SrijanShovit/carbonops-v2/commit/2544b06d742369040af95bfa8c65cd620bb5b925)) [21:42:07.821] Cloning completed: 298.307ms [21:42:10.710] Restored build cache [21:42:10.739] Running "vercel build" [21:42:11.254] Vercel CLI 29.3.6 [21:42:11.528] Installing dependencies... [21:42:13.213] [21:42:13.214] added 1 package in 1s [21:42:13.214] [21:42:13.214] 136 packages are looking for funding [21:42:13.214] run `npm fund` for details [21:42:13.225] Detected Next.js version: 13.4.2 [21:42:13.227] Detected `package-lock.json` generated by npm 7+... [21:42:13.228] Running "npm run build" [21:42:13.538] [21:42:13.538] > carbonops-v2@0.1.0 build [21:42:13.538] > next build [21:42:13.539] [21:42:14.081] - info Creating an optimized production build... [21:42:22.797] Failed to compile. [21:42:22.797] [21:42:22.797] ./components/homepage/Services.js [21:42:22.797] Module not found: Can't resolve '../../public/images/homepage/interview.png' [21:42:22.798] [21:42:22.798] https://nextjs.org/docs/messages/module-not-found [21:42:22.798] [21:42:22.798] Import trace for requested module: [21:42:22.798] ./app/page.js [21:42:22.798] [21:42:22.798] [21:42:22.799] > Build failed because of webpack errors [21:42:22.839] Error: Command "npm run build" exited with 1 [21:42:23.031] BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
> 
> Problem in deployment

@SrijanShovit @shreya024 
I fixed the bugs from this error log.
I request you to please solve this error for me.
I am trying to pass the vercel test but I am unable to do so. I don't know why this is happening but I am trying my best to fix this. I have worked hard to implement the `Signup Pages` for the website.
Please help me out!

2023-05-29 01:31 UTC, shreya024 commented on components/homepage/Services.js
> +import serviceImage2 from "../../public/images/homepage/interview.png";
Change `import serviceImage2 from "../../public/images/homepage/interview.png"` to `import serviceImage2 from "../../public/images/homepage/Interview.png"

2023-05-29 01:33 UTC, MahendraDani commented on components/homepage/Services.js
> +import serviceImage2 from "../../public/images/homepage/interview.png";
But the file name of the image is saved as `interview.png` in the file directory.

2023-05-29 01:34 UTC, shreya024 commented
> > @shreya024 [21:42:07.464] Running build in Washington, D.C., USA (East) – iad1 [21:42:07.523] Cloning github.com/SrijanShovit/carbonops-v2 (Branch: Mahendra/signup_page_branch, Commit: [2544b06](https://github.com/SrijanShovit/carbonops-v2/commit/2544b06d742369040af95bfa8c65cd620bb5b925)) [21:42:07.821] Cloning completed: 298.307ms [21:42:10.710] Restored build cache [21:42:10.739] Running "vercel build" [21:42:11.254] Vercel CLI 29.3.6 [21:42:11.528] Installing dependencies... [21:42:13.213] [21:42:13.214] added 1 package in 1s [21:42:13.214] [21:42:13.214] 136 packages are looking for funding [21:42:13.214] run `npm fund` for details [21:42:13.225] Detected Next.js version: 13.4.2 [21:42:13.227] Detected `package-lock.json` generated by npm 7+... [21:42:13.228] Running "npm run build" [21:42:13.538] [21:42:13.538] > carbonops-v2@0.1.0 build [21:42:13.538] > next build [21:42:13.539] [21:42:14.081] - info Creating an optimized production build... [21:42:22.797] Failed to compile. [21:42:22.797] [21:42:22.797] ./components/homepage/Services.js [21:42:22.797] Module not found: Can't resolve '../../public/images/homepage/interview.png' [21:42:22.798] [21:42:22.798] https://nextjs.org/docs/messages/module-not-found [21:42:22.798] [21:42:22.798] Import trace for requested module: [21:42:22.798] ./app/page.js [21:42:22.798] [21:42:22.798] [21:42:22.799] > Build failed because of webpack errors [21:42:22.839] Error: Command "npm run build" exited with 1 [21:42:23.031] BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
> > Problem in deployment
> 
> @SrijanShovit @shreya024 I fixed the bugs from this error log. I request you to please solve this error for me. I am trying to pass the vercel test but I am unable to do so. I don't know why this is happening but I am trying my best to fix this. I have worked hard to implement the `Signup Pages` for the website. Please help me out!

Hey @MahendraDani Don't worry.Your PR will be merged.and we are with you to provide all the help you need to solve these kind of errors.Consider this as a part of the learning process.

2023-05-29 01:39 UTC, MahendraDani commented
@shreya024 I have checked on my local development server. All the images are properly displayed and there is no error in neither the terminal nor the console.

Yesterday I changed the file name of `serviceImage2` as `interview.png` which makes the import path correct. So there should not be any error in tha file path?

2023-05-29 02:01 UTC, shreya024 commented
> @shreya024 I have checked on my local development server. All the images are properly displayed and there is no error in neither the terminal nor the console.
> 
> Yesterday I changed the file name of `serviceImage2` as `interview.png` which makes the import path correct. So there should not be any error in tha file path?

in the images folder it is saved as Interview.png right?...that's the vercel error here it cannot find 'interview.png'

2023-05-29 02:03 UTC, MahendraDani commented
@shreya024 Now I have changed the path to the one mentioned by you.
I think there is some issue in vercel deployments that is failing the tests, because if there were any errors in my code then it would have shown in my development server but when I am checking on my development server I see no errors and then I push the commit but after that the vercel test fails here, which is why I am not able understand what the error is exactly?!!

2023-05-29 02:34 UTC, shreya024 commented
@MahendraDani In ./components/homepage/Hero.js change `../../public/images/homepage/hero.png` to `../../public/images/homepage/Hero.png`
In ./app/signup/page.js
In lines 31 and 62 change ' to &apos;

2023-05-29 02:34 UTC, shreya024 commented
> @MahendraDani In ./components/homepage/Hero.js change `../../public/images/homepage/hero.png` to `../../public/images/homepage/Hero.png` In ./app/signup/page.js In lines 31 and 62 change ' to `&apos;`

2023-05-29 02:45 UTC, MahendraDani commented
@shreya024 Mam all checks are passed this time.
I can't thank you enough for helping me out!

I am extremely sorry for the 
inconvenience cause during the process.

I will try my best to not make such mistakes again.
Thanks a lot!

2023-05-29 03:45 UTC, shreya024 approved these changes
Good job 👏 @MahendraDani

2023-05-29 03:45 UTC, merged

2023-05-29 03:50 UTC, MahendraDani commented
@shreya024 Thanks mam!
Thanks a lot for providing help throughout the process!