fix: Refractored the README.md and added animated thank you gif
SrijanShovit/carbonops-v2 pull request #56
Opened 2023-05-31 09:17 UTC by MahendraDani

## Related Issue

Closes: #28 

## Description of Changes

Clearly and concisely describe the modifications made to successfully resolve the assigned issue. Include any pertinent information about new files or any other relevant details.
### Major changes
1. Added animated `thank-you gif` in README.md file. 

### Minor changes
1. Refractor the instructions for setting up the project locally. New contributors would be able to follow and understand the instructions easily.
2. Enhnaced the `documentation` section of the file

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots/Videos

### **1. Set up instructions**

### Before

![issue_carbonops_setup](https://github.com/SrijanShovit/carbonops-v2/assets/116940083/d379f90a-cba8-4102-bf73-ec6b9fe78fa2)
### After
![fix_carbonops_setup](https://github.com/SrijanShovit/carbonops-v2/assets/116940083/1fe8a743-8652-47ef-8baf-c02f253ac048)

### **2.`Documentation` section**
### Before
![issue_carbonops_readme_doc](https://github.com/SrijanShovit/carbonops-v2/assets/116940083/bf74bf6f-43f2-4ae2-af8c-18cb59cd599a)

### After
![fix_carbonops_readme_doc](https://github.com/SrijanShovit/carbonops-v2/assets/116940083/fbfdef4c-00b4-41bf-9ed4-a271a2743598)

### **4.Animated thank you gif**

https://github.com/SrijanShovit/carbonops-v2/assets/116940083/83bb1232-8da3-49de-8230-80a947fb8658

### Preview gif

![thankyou](https://github.com/SrijanShovit/carbonops-v2/assets/116940083/f613df6c-186c-4c8d-8df1-8443e081728c)

2023-05-31 09:18 UTC, MahendraDani commented
@shreya024 If there are any changes please let me know.
P.S : I created the gif myself
Thanks!

2023-05-31 14:37 UTC, SrijanShovit commented
Instead of the gif, please implement an animation of at least simple left to right running thank you

2023-05-31 14:39 UTC, MahendraDani commented
> Instead of the gif, please implement an animation of at least simple left to right running thank you

@SrijanShovit I will try!

2023-05-31 15:17 UTC, MahendraDani commented
@SrijanShovit @shreya024 
I tried to add left to right animation as you said but it does not work in markdown files.

Please take a look at the following video-

https://github.com/SrijanShovit/carbonops-v2/assets/116940083/4667d81b-6c36-4984-8934-169dfbcac6e6

- I created a repo to test the animation.
- You can see in the video that I have used `style tags` and added animation using `@keyframes` which seems to be working in my editor.
- But this animation does not work on the remote repo. 
- Take a look at the following screenshot of my testing repo
![Untitled design (2)](https://github.com/SrijanShovit/carbonops-v2/assets/116940083/7fabae94-8d2a-4f97-a85f-113acaf78c25)

- You can observe that on the repo's README file no such animation is working. And the styles are always displayed which should not happen.

2023-05-31 15:18 UTC, MahendraDani commented
@shreya024 @SrijanShovit 
I think that an animation like that can't be added in Markdown files.

2023-06-01 07:04 UTC, MahendraDani commented
> @shreya024 @SrijanShovit 
> I think that an animation like that can't be added in Markdown files.
> 

@SrijanShovit @shreya024 I think the gif will also be fine because the animation can't be made!
Please let me know your views!
Thanks.

2023-06-02 01:41 UTC, MahendraDani commented
@shreya024 @SrijanShovit Please review this PR!

2023-06-02 04:49 UTC, SrijanShovit commented
@MahendraDani @shreya024 For now proceed with the gif. If later some better solution comes we shall add it.

2023-06-02 04:51 UTC, MahendraDani commented
@SrijanShovit Alright!
Thanks!

2023-06-02 04:51 UTC, shreya024 commented
@MahendraDani PR has merge conflicts.Take a pull,resolve the conflicts and then push again.

2023-06-02 04:52 UTC, MahendraDani commented
@shreya024 Okay I will take a pull then push it again in a minute

2023-06-02 04:58 UTC, MahendraDani commented
@shreya024 Is everything fine from my side now? I resolved the conflicts.

2023-06-02 16:08 UTC, shreya024 approved these changes

2023-06-02 16:14 UTC, shreya024 requested changes

2023-06-02 16:14 UTC, shreya024 commented on README.md
> +<<<<<<< HEAD
Remove this line

2023-06-02 16:14 UTC, shreya024 commented on README.md
> +=======
Remove this line

2023-06-02 16:14 UTC, shreya024 commented on README.md
>  1. `git clone https://github.com/SrijanShovit/Carbonops-v2.git`
Remove lines 97,98

2023-06-02 16:28 UTC, MahendraDani commented on README.md
>  1. `git clone https://github.com/SrijanShovit/Carbonops-v2.git`
> Remove lines 97,98

@shreya024 Removing lines 97,98

2023-06-02 16:33 UTC, MahendraDani commented
@shreya024 Please let me know if there are any changes now!

2023-06-03 01:24 UTC, merged