Fixed navbar
SrijanShovit/carbonops-v2 pull request #61
Opened 2023-06-01 10:49 UTC by kedar1998

## Related Issue
Logo image in top navbar was not loading. Due to which height of navbar was increasing.

Closes: #47

## Description of Changes
- Logo image in top navbar was not loading.  Due to which height of navbar was increasing. I have fixed that issue. It was due to naming convention of image file.
- Reference of solution - https://stackoverflow.com/questions/65155729/next-image-component-throws-404-error-in-production-works-fine-in-development

## Checklist:
- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| ![image](https://github.com/SrijanShovit/carbonops-v2/assets/103363619/2c2e21cc-2b2b-4cb9-bde0-bc79ecc478fb) | 
![image](https://github.com/SrijanShovit/carbonops-v2/assets/103363619/e901a46a-d19c-49df-9c9d-429b9063ec6c)
 |

2023-06-02 01:07 UTC, shreya024 requested changes
The issue is still not fixed.The unnecessary space is still there in vercel percel.
@kedar1998 Try importing images and then placing them in src,as for width and height try using % or rem

2023-06-02 01:08 UTC, shreya024 commented
> The issue is still not fixed.The unnecessary space is still there in vercel preview. @kedar1998 Try importing images and then placing them in src,as for width and height try using % or rem

2023-06-05 04:01 UTC, kedar1998 commented
Working on it

2023-06-05 04:17 UTC, kedar1998 commented
@shreya024 can you check if issue is fixed in production? I have made some changes

2023-06-06 00:54 UTC, shreya024 commented
> @shreya024 can you check if issue is fixed in production? I have made some changes

@kedar1998 Resolve the merge conflicts and push again

2023-06-14 01:49 UTC, shreya024 commented
@kedar1998 Resolve the conflicts by this week,else issue will ne reassigned

2023-07-09 05:55 UTC, closed without merging